import type { UIIcon } from "@app/plugin-sdk";
import {
  AlertTriangle,
  ArrowUp,
  Camera,
  Check,
  Info,
  Lightbulb,
  Lock,
  type LucideIcon,
  MapPin,
  Megaphone,
  MessagesSquare,
  Plus,
  RotateCcw,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
} from "lucide-react-native";

/** The icons a node can show, keyed by the names in packages/sdk (UI_ICONS). */
export const UI_ICON: Record<UIIcon, LucideIcon> = {
  alert: AlertTriangle,
  idea: Lightbulb,
  camera: Camera,
  megaphone: Megaphone,
  share: Share2,
  send: Send,
  pin: MapPin,
  chat: MessagesSquare,
  plus: Plus,
  lock: Lock,
  shield: ShieldCheck,
  settings: Settings,
  sliders: SlidersHorizontal,
  check: Check,
  refresh: RotateCcw,
  info: Info,
  arrowUp: ArrowUp,
  sparkles: Sparkles,
};
