import type { Clip, Still } from "../ads/shared/media";

/**
 * The login screen's looping video, in three variants (a, b, c), from media generated by scripts/media.ts: a still
 * per shot with the Gemini image model, then a Veo clip that opens on it, so each shot keeps the still's framing and
 * light. Every shot is 16:9 with its subject in the middle third, because the loop crops it to a square.
 * Variant b's city is a still that the loop slowly pushes in on (Loop.tsx). Variant c dives from the city down onto the square of the handshake (a Veo clip from its first to its last still;
 * the clip cuts to another scene halfway, so the loop keeps only the dive, see Loop.tsx).
 */
const LOOK =
  "Photorealistic cinematic film still, 16:9, natural light, gentle contrast, true-to-life colours. The main subject is in the middle third of the frame. No text, no captions, no logos, no watermark.";
const SQUARE = "The action stays in the middle third of the frame.";
const MOTION = "Realistic natural motion, one continuous shot without cuts, no text, no logos.";

export const LOGIN_MEDIA = {
  // a: a summer evening in golden light.
  "a-miasto": {
    kind: "image",
    file: "login/stills/a-miasto.jpg",
    prompt: `Aerial drone photo at golden hour over the old town of a historic Polish city: a large market square with a Gothic town hall tower, a red-brick Gothic church with two towers, colourful tenement houses with red-tiled roofs, a ring of green park around the old town and a river with bridges in the distance. Warm low sun, long shadows, light haze. ${LOOK}`,
  },
  "a-dlonie": {
    kind: "image",
    file: "login/stills/a-dlonie.jpg",
    prompt: `Golden hour in the green courtyard of an old Polish tenement house with ochre plaster walls, wooden benches, red geraniums in window boxes and a big chestnut tree. A woman in her early thirties in a linen shirt reaches out to shake hands with an elderly woman in her late seventies with short grey hair, glasses and a knitted cardigan, who holds a smartphone in her other hand. Both smile warmly. They stand facing each other in profile, medium two-shot from the waist up, their hands about to meet in the exact centre of the frame. Shallow depth of field. ${LOOK}`,
  },
  "a-miasto-lot": {
    kind: "video",
    file: "login/clips/a-miasto.mp4",
    first: "a-miasto",
    prompt: `Smooth slow cinematic drone flight forward over the old town at golden hour, gently descending towards the market square, warm sunlight on the roofs, a few birds fly by. ${SQUARE} ${MOTION}`,
  },
  "a-dlonie-uscisk": {
    kind: "video",
    file: "login/clips/a-dlonie.mp4",
    first: "a-dlonie",
    prompt: `The two women step closer and shake hands warmly, smiling and nodding to each other; the elderly woman keeps holding her smartphone in her other hand. Slow gentle push-in on the handshake, golden hour light, leaves moving in the breeze. ${SQUARE} ${MOTION}`,
  },

  // b: a sunny Polish autumn morning.
  "b-miasto": {
    kind: "image",
    file: "login/stills/b-miasto.jpg",
    prompt: `Aerial drone photo on a crisp sunny autumn morning over a Polish city on a wide river: several bridges, a historic district with church spires and tenement houses on one bank, parks full of yellow and orange trees, a few modern glass office towers in the distance, soft morning mist over the water. ${LOOK}`,
  },
  "b-dlonie": {
    kind: "image",
    file: "login/stills/b-dlonie.jpg",
    prompt: `A sunny autumn morning on a green Polish housing estate: renovated pastel-coloured blocks of flats, yellow birch and maple leaves on the lawn, a bench and a playground in the background. A young woman in her late twenties in a wool coat and scarf shakes hands with a smiling elderly woman of about eighty in a beret and a warm coat, who holds a smartphone in her other hand. Medium two-shot from the waist up, both in profile facing each other, their clasped hands in the exact centre of the frame. Shallow depth of field, warm morning sun. ${LOOK}`,
  },
  "b-dlonie-uscisk": {
    kind: "video",
    file: "login/clips/b-dlonie.mp4",
    first: "b-dlonie",
    prompt: `The two women shake hands warmly and smile at each other, the elderly woman laughs and lifts her smartphone a little in her other hand as if to show it; autumn leaves fall slowly in the sunlight. Slow gentle push-in. ${SQUARE} ${MOTION}`,
  },

  // c: a summer day, one move from the sky down to the handshake.
  "c-miasto": {
    kind: "image",
    file: "login/stills/c-miasto.jpg",
    prompt: `Aerial drone photo high above a historic district of a Polish city on a bright summer day: tree-lined streets, rows of old tenement houses with inner courtyards, a tram line, a small square with café umbrellas and trees in the centre of the frame. Soft sunlight, light haze. ${LOOK}`,
  },
  "c-dlonie": {
    kind: "image",
    file: "login/stills/c-dlonie.jpg",
    prompt: `A bright summer day on a small tree-lined square among old tenement houses in a Polish city, café umbrellas and plane trees in the soft background. A woman in her mid thirties in a light summer dress shakes hands with a smiling elderly woman in her late seventies with white hair and a cardigan, who holds a smartphone in her other hand. Their hands are clasped in the exact centre of the frame, medium two-shot from the waist up, both in profile facing each other, warm and friendly. Shallow depth of field, dappled sunlight. ${LOOK}`,
  },
  "c-szkola": {
    kind: "image",
    file: "login/stills/c-szkola.jpg",
    prompt: `The entrance to the school gym inside a Polish secondary school on a summer morning: a corridor with a light terrazzo floor and sunlit windows, the wooden double doors of the gym half open, a gym with wall bars and a volleyball net inside. On the wall next to the doors hangs a small framed sign with one big QR code. A sixteen-year-old boy in a T-shirt with a backpack on one shoulder raises his smartphone to the QR code. Three-quarter view from behind, his phone and the QR code in the centre of the frame, the phone screen not visible. ${LOOK}`,
  },
  "c-miasto-zjazd": {
    kind: "video",
    file: "login/clips/c-miasto.mp4",
    first: "c-miasto",
    last: "c-dlonie",
    prompt: `One continuous cinematic drone move: the camera glides forward high over the summer city, then smoothly dives down between the trees into the small square and ends at eye level on two women shaking hands. ${MOTION}`,
  },
  "c-dlonie-uscisk": {
    kind: "video",
    file: "login/clips/c-dlonie.mp4",
    first: "c-dlonie",
    prompt: `The two women keep shaking hands warmly, smile and say a few friendly words; the elderly woman holds her smartphone in her other hand. The camera slowly drifts around them, dappled summer sunlight, leaves moving in the breeze. ${SQUARE} ${MOTION}`,
  },
  "c-szkola-qr": {
    kind: "video",
    file: "login/clips/c-szkola.mp4",
    first: "c-szkola",
    prompt: `The boy holds his phone up to the QR code next to the gym doors, the phone screen gives a soft glow, he smiles and walks through the doors into the gym. The camera follows him slowly. ${SQUARE} ${MOTION}`,
  },
} as const satisfies Record<string, Still | Clip>;
