/**
 * All UI text of the app (Polish — the app has one language). Import `t` and read `t.key`;
 * no Polish string literals in components.
 */
export const t = {
  dashboard_greeting: "Dzień dobry",
  dashboard_empty_label: "Brak miejsc na koncie",
  dashboard_empty_title: "Dołącz do swojego pierwszego miejsca",
  join_methods_title: "Jak chcesz dołączyć?",
  join_qr: "Zeskanuj kod QR",
  join_qr_hint: "Z plakatu, tablicy lub ekranu",
  join_code: "Wpisz kod zaproszeniowy",
  join_code_hint: "6-znakowy kod od administratora",
  join_link: "Wklej link",
  join_link_hint: "Link z wiadomości lub e-maila",
  join_invites: "Zaproszenia",
  join_invites_hint: "Od innych użytkowników",
  join_map: "Znajdź na mapie",
  join_map_hint: "Miejsca w Twojej okolicy",
  place_create_own: "Utwórz własne miejsce",
  place_create: "Utwórz nowe",
  place_join: "Dołącz",
  place_current_label: "Twoje miejsce",
  place_set_default: "Ustaw wybrane jako domyślne",
  places_sheet_title: "Twoje miejsca",
  widgets_empty_title: "Pulpit jest jeszcze pusty",
  widgets_empty_body: "Wkrótce pojawią się tu widżety tego miejsca.",
  create_title: "Nowe miejsce",
  create_cancel: "Anuluj",
  create_next: "Dalej",
  create_step_1: "Krok 1 z 4",
  create_step_2: "Krok 2 z 4",
  create_step_3: "Krok 3 z 4",
  create_step_4: "Krok 4 z 4",
  create_kind_title: "Jakie miejsce tworzysz?",
  create_kind_lead: "Rodzaj pomoże dobrać widżety na pulpicie.",
  create_kinds_label: "Rodzaj miejsca",
  place_kind_estate: "Osiedle",
  place_kind_estate_hint: "Mieszkańcy kilku budynków",
  place_kind_building: "Budynek",
  place_kind_building_hint: "Kamienica, blok, wspólnota",
  place_kind_company: "Firma",
  place_kind_company_hint: "Biuro, zespół, coworking",
  place_kind_school: "Szkoła",
  place_kind_school_hint: "Szkoła, uczelnia, kampus",
  place_kind_district: "Dzielnica",
  place_kind_district_hint: "Okolica, sołectwo, gmina",
  place_kind_other: "Inne",
  place_kind_other_hint: "Klub, parafia, wydarzenie",
  create_details_title: "Opisz swoje miejsce",
  create_details_lead: "Te dane zobaczą osoby, które dołączą.",
  create_name: "Nazwa miejsca",
  create_address: "Adres",
  create_address_placeholder: "np. ul. Lipowa 12, Kraków",
  create_location_label: "Lokalizacja (opcjonalnie)",
  create_location_pick: "Wskaż na mapie",
  create_location_hint: "Pinezka pozwoli znaleźć miejsce na mapie miejsc.",
  create_location_change: "Zmień lokalizację",
  create_location_remove: "Usuń lokalizację",
  create_location_preview: "Lokalizacja miejsca na mapie",
  create_description: "Krótki opis (opcjonalnie)",
  create_description_placeholder: "np. Wspólnota mieszkaniowa — ogłoszenia, awarie, zebrania.",
  create_features_title: "Co ma działać w tym miejscu?",
  create_features_lead: "Wybierz funkcje, z których będą korzystać członkowie. Zaznacz co najmniej jedną.",
  create_features_label: "Funkcje miejsca",
  create_features_error: "Nie udało się pobrać listy funkcji.",
  create_access_title: "Kto może dołączyć?",
  create_access_lead: "Możesz to zmienić w każdej chwili.",
  join_rules_label: "Zasady dołączania",
  join_rule_open: "Otwarte",
  join_rule_open_hint: "Każdy z kodem, linkiem lub QR dołącza od razu.",
  join_rule_approval: "Z akceptacją",
  join_rule_approval_hint: "Zatwierdzasz każdą prośbę o dołączenie.",
  join_rule_invite: "Tylko zaproszenia",
  join_rule_invite_hint: "Dołączają wyłącznie osoby zaproszone przez Ciebie.",
  badge_recommended: "Polecane",
  create_make_default: "Ustaw jako domyślne miejsce",
  create_on_map: "Pokaż na mapie miejsc",
  create_on_map_hint:
    "Każdy zalogowany użytkownik zobaczy nazwę, rodzaj i adres miejsca, a do otwartego miejsca dołączy prosto z mapy. Członkowie widzą je zawsze.",
  create_admin_note_before: "Zostaniesz ",
  create_admin_note_role: "administratorem",
  create_admin_note_after: " tego miejsca. Później możesz nadać te uprawnienia innym osobom.",
  create_submit: "Utwórz miejsce",
  create_error: "Nie udało się utworzyć miejsca.",
  created_title_before: "Miejsce „",
  created_title_after: "” jest gotowe",
  created_admin: "Jesteś administratorem",
  created_go_dashboard: "Przejdź do pulpitu",
  invite_code_label: "Kod zaproszeniowy",
  invite_code_hint: "Wydrukuj kod QR i powieś go w widocznym miejscu.",
  invite_qr_label: "Kod QR miejsca",
  invite_share: "Udostępnij",
  invite_share_message_before: "Dołącz do miejsca „",
  invite_share_message_after: "” w aplikacji Twoje Miejsce. Kod zaproszeniowy:",
  join_title: "Dołącz do miejsca",
  join_body: "Dołączanie do miejsca będzie dostępne wkrótce.",
  account_title: "Konto",
  account_places_label: "Twoje miejsca",
  account_notifications_label: "Powiadomienia",
  account_notifications_empty: "Nie masz jeszcze powiadomień. Tu zobaczysz wiadomości od rozszerzeń Twoich miejsc.",
  account_notifications_read_all: "Oznacz wszystkie jako przeczytane",
  account_notifications_more: "Pokaż wszystkie",
  account_notifications_less: "Pokaż mniej",
  account_notification_unread: "nieprzeczytane",
  account_nearby_label: "Powiadomienia w okolicy",
  account_nearby_body:
    "Rozszerzenia Twoich miejsc mogą ostrzegać o sprawach w pobliżu. Dodaj adresy, przy których chcesz dostawać takie powiadomienia, np. dom albo pracę.",
  account_nearby_private: "Te adresy zna tylko aplikacja: nie widzą ich rozszerzenia ani inni mieszkańcy.",
  account_nearby_empty: "Nie masz jeszcze zapisanych adresów.",
  account_nearby_add: "Dodaj adres",
  account_nearby_limit: "Osiągnięto limit adresów",
  account_nearby_remove: "Usuń adres",
  account_nearby_picker_title: "Adres do powiadomień",
  account_nearby_pin_hint: "tu dotrą powiadomienia o sprawach w okolicy",
  account_nearby_new: "Nowy adres",
  account_nearby_name: "Nazwa",
  account_nearby_name_placeholder: "np. Działka",
  account_nearby_suggestions: "Podpowiedzi nazwy",
  account_nearby_home: "Dom",
  account_nearby_work: "Praca",
  account_nearby_school: "Szkoła",
  account_nearby_family: "Rodzina",
  account_nearby_save: "Zapisz adres",
  account_nearby_error: "Nie udało się zapisać adresu. Spróbuj ponownie.",
  account_app_label: "Aplikacja",
  account_permissions: "Uprawnienia",
  account_permissions_hint: "Powiadomienia, aparat i lokalizacja w ustawieniach telefonu",
  back: "Wróć",
  tab_dashboard: "Pulpit",
  tab_places: "Miejsca",
  tab_map: "Mapa",
  tab_account: "Konto",
  nav_main: "Nawigacja główna",
  close: "Zamknij",
  search_clear: "Wyczyść",
  location_title: "Lokalizacja miejsca",
  location_search: "Szukaj adresu",
  location_results: "Wyniki wyszukiwania",
  location_searching: "Szukam…",
  location_no_results: "Nie znaleziono adresu. Spróbuj inaczej albo wskaż miejsce na mapie.",
  location_search_error: "Nie udało się wyszukać adresu. Wskaż miejsce na mapie.",
  location_hint: "Dotknij mapy lub przesuń ją, aby ustawić pinezkę",
  location_my: "Moja lokalizacja",
  location_my_unavailable: "Nie udało się ustalić Twojej lokalizacji.",
  location_looking_up: "Szukam adresu…",
  location_unknown: "Wybrany punkt na mapie",
  location_pin_hint: "tu pojawi się pinezka miejsca",
  location_confirm: "Potwierdź lokalizację",
  map_title: "Mapa miejsc",
  map_label: "Mapa",
  dashboard_map_label: "Mapa miejsca",
  map_list_label: "Miejsca na mapie",
  map_empty: "Na mapie nie ma jeszcze miejsc. Utwórz miejsce, wskaż je na mapie i pokaż je innym.",
  map_error: "Nie udało się pobrać mapy miejsc.",
  map_member: "Twoje",
  map_open_place: "Otwórz miejsce",
  /** On the card of an open place for a non-member: opens its preview, where they join. */
  map_join_place: "Dołącz",
  map_join_hint: "Aby dołączyć, poproś administratora o kod zaproszenia.",
  place_preview_title: "Podgląd miejsca",
  place_preview_code: "Kod miejsca",
  place_preview_default: "Ustaw jako domyślne",
  place_preview_join: "Dołącz do miejsca",
  place_preview_approval:
    "Dołączenie do tego miejsca wymaga zgody administratora. Ta możliwość nie jest jeszcze dostępna.",
  place_preview_not_found: "Nie znaleziono miejsca dla tego kodu.",
  place_preview_error: "Nie udało się dołączyć do miejsca. Spróbuj ponownie.",
  join_code_title: "Dołącz kodem lub linkiem",
  join_code_lead: "Kod otrzymasz od administratora miejsca.",
  join_tab_code: "Kod",
  join_tab_link: "Link",
  join_code_label: "Kod zaproszeniowy",
  join_code_char: "Znak",
  join_code_case_hint: "Wielkość liter nie ma znaczenia.",
  join_link_label: "Link zaproszeniowy",
  join_link_placeholder: "https://twojemiejsce.pl/z/…",
  join_submit: "Dalej",
  join_invalid: "To nie wygląda na kod ani link zaproszeniowy.",
  join_not_found: "Nie znaleziono miejsca dla tego kodu.",
  invites_title: "Zaproszenia",
  invites_lead: "Inni użytkownicy zaprosili Cię do swoich miejsc.",
  invites_empty: "Nie masz żadnych zaproszeń.",
  invite_accept: "Akceptuj",
  invite_decline: "Odrzuć",
  invite_error: "Nie udało się wykonać tej czynności. Spróbuj ponownie.",
  time_just_now: "przed chwilą",
  time_minutes_ago: "min temu",
  time_hours_ago: "godz. temu",
  time_yesterday: "wczoraj",
  /** "3 dni temu" (2–6 days), "1 tydz. temu", "2 tyg. temu" (up to 5 weeks; older times are dates). */
  time_days_ago: "dni temu",
  time_week_ago: "tydz. temu",
  time_weeks_ago: "tyg. temu",
  time_now: "teraz",
  time_minutes: "min",
  time_hours: "godz.",
  join_hero_label: "Twoje miejsca",
  join_hero_title: "Dołącz do miejsca",
  scan_title: "Skanuj kod",
  scan_hint: "Skieruj aparat na kod QR miejsca. Rozpoznamy go automatycznie.",
  scan_torch: "Latarka",
  scan_enter_code: "Wpisz kod ręcznie",
  scan_permission_allow: "Zezwól na dostęp do aparatu",
  scan_permission_settings: "Otwórz ustawienia",
  scan_permission_denied: "Brak dostępu do aparatu. Zmień uprawnienia w ustawieniach telefonu.",
  place_default_badge: "Domyślne",
  app_name: "Twoje Miejsce",
  meta_login_title: "Logowanie — Twoje Miejsce",
  meta_register_title: "Załóż konto — Twoje Miejsce",
  nav_label: "Główna",
  nav_login: "Zaloguj się",
  nav_open_app: "Otwórz aplikację",
  auth_login_title: "Witaj z powrotem",
  auth_login_lead: "Zaloguj się, aby zobaczyć swoje miejsca.",
  auth_register_title: "Załóż konto",
  auth_name: "Imię i nazwisko",
  auth_email: "Adres e-mail",
  auth_password: "Hasło",
  auth_submit_login: "Zaloguj się",
  auth_submit_register: "Utwórz konto",
  auth_have_account: "Masz już konto?",
  auth_no_account: "Nie masz konta?",
  auth_goto_login: "Zaloguj się",
  auth_goto_register: "Zarejestruj się",
  auth_login_error: "Nieprawidłowy email lub hasło.",
  /** Dev login buttons (EXPO_PUBLIC_DEV_LOGIN); followed by a seeded account's email (demo admin, demo resident). */
  auth_dev_login: "Dev: zaloguj jako",
  auth_register_error: "Nie udało się założyć konta. Ten email może być już zajęty.",
  auth_register_lead: "Jedno konto — wszystkie Twoje miejsca w jednej aplikacji.",
  auth_step: "Krok 1 z 2",
  auth_back: "Wróć",
  auth_name_placeholder: "Jan Kowalski",
  auth_email_placeholder: "jan.kowalski@poczta.pl",
  auth_password_placeholder: "Minimum 5 znaków",
  pw_hint_length: "Użyj co najmniej 5 znaków.",
  pw_ok: "Hasło spełnia wymagania.",
  auth_password_too_short: "Hasło musi mieć co najmniej 5 znaków.",
  auth_consent: "Akceptuję regulamin i politykę prywatności.",
  auth_consent_required: "Zaakceptuj regulamin, aby założyć konto.",
  auth_google: "Google",
  auth_google_consent: "Logując się przez Google, akceptujesz regulamin i politykę prywatności.",
  auth_google_exists: "Ten adres e-mail ma już konto z hasłem. Zaloguj się e-mailem i hasłem.",
  auth_google_error: "Nie udało się zalogować przez Google. Spróbuj ponownie.",
  loading: "Ładowanie…",
  sign_out: "Wyloguj",
  notfound_title: "Ta strona nie istnieje",
  notfound_body: "Link może być błędny albo strona została usunięta.",
  notfound_home: "Przejdź na stronę główną",
  meta_notfound_title: "Nie znaleziono strony — Twoje Miejsce",
  community_dashboard_label: "Pulpit miejsca",
  /** Screen-reader action on a widget tile (sighted admins long-press the tile). */
  dashboard_edit: "Edytuj pulpit",
  /** A widget tile's accessible name: "Otwórz: Zgłoszenia". */
  dashboard_open: "Otwórz",
  dashboard_done: "Gotowe",
  dashboard_edit_hint: "Przeciągnij kafelek albo użyj strzałek. Kolejność zobaczą wszyscy mieszkańcy.",
  dashboard_drag: "Przeciągnij",
  dashboard_move_earlier: "Przesuń wcześniej",
  dashboard_move_later: "Przesuń dalej",
  dashboard_save_error: "Nie udało się zapisać kolejności. Spróbuj ponownie.",
  plugin_load_error: "Nie udało się wczytać tej funkcji.",
  plugin_action_error: "Coś poszło nie tak. Sprawdź formularz i spróbuj ponownie.",
  plugin_unsupported: "Ten element wymaga nowszej wersji aplikacji.",
  plugin_activity_new: "Nowe",
  plugin_chat_you: "Ty",
  cancel: "Anuluj",
  plugin_photo_camera: "Aparat",
  plugin_photo_gallery: "Galeria",
  plugin_photo_add: "Dodaj",
  plugin_photo_remove: "Usuń zdjęcie",
  plugin_photo_uploading: "Wysyłanie zdjęcia…",
  plugin_photo_error: "Nie udało się wysłać zdjęcia. Spróbuj ponownie.",
  plugin_photo_preview: "Wybrane zdjęcie",
  plugin_location_pick: "Wskaż na mapie",
  plugin_location_change: "Zmień",
  plugin_location_remove: "Usuń miejsce",
  plugin_location_preview: "Wybrane miejsce na mapie",
  plugin_location_hint: "Tu pojawi się pinezka",
  plugin_map_list_show: "Pokaż listę",
  plugin_map_list_hide: "Ukryj listę",
  plugin_map_legend: "Legenda mapy",
  plugin_progress: "Postęp zgłoszenia",
  /** The "+N" badge on a thumbnail: "Dodatkowe zdjęcia: 2". */
  plugin_photos_more: "Dodatkowe zdjęcia",
  /** A photo's position: "Zdjęcie 1 z 3" (a gallery page, a picked photo). */
  plugin_photo_number: "Zdjęcie",
  plugin_photo_of: "z",
  /** The remove button of a tag: "Usuń: Oświetlenie". */
  plugin_tag_remove: "Usuń",
  // A plugin's page in "Zarządzaj miejscem" (design Z-StronaPluginu)
  plugin_page_eyebrow: "Rozszerzenie",
  plugin_page_widget: "Widżet rozszerzenia",
  plugin_page_on_dashboard: "Na pulpicie",
  plugin_page_off_dashboard: "Poza pulpitem",
  plugin_page_not_found: "Tego rozszerzenia nie ma w tym miejscu.",
  plugin_page_remove: "Usuń rozszerzenie z miejsca",
  plugin_page_remove_title: "Usunąć rozszerzenie z miejsca?",
  plugin_page_remove_body:
    "Zniknie z pulpitu i nawigacji miejsca. Jego dane zostaną zachowane i wrócą, gdy dodasz je ponownie.",
  plugin_page_remove_confirm: "Usuń",
  plugin_page_remove_error: "Nie udało się usunąć rozszerzenia.",
  // Managing a place (design E-ZarzadzanieMiejscem), for its admins
  manage_title: "Zarządzaj miejscem",
  manage_admins_only: "Tylko administratorzy mogą zarządzać tym miejscem.",
  manage_load_error: "Nie udało się wczytać tego miejsca.",
  manage_invites_title: "Zaproszenia",
  manage_invites_code: "Kod",
  manage_invites_rest: "QR · zaproszenia",
  manage_invite_lead: "Zaproś osobę, która ma już konto w aplikacji.",
  manage_invite_email: "E-mail osoby",
  manage_invite_send: "Zaproś",
  manage_invite_sent: "Zaproszenie wysłane.",
  manage_invite_no_account: "Nikt nie ma konta z tym adresem e-mail.",
  manage_invite_conflict: "Ta osoba już należy do miejsca albo ma zaproszenie.",
  manage_invite_error: "Nie udało się wysłać zaproszenia.",
  manage_plugins_title: "Rozszerzenia",
  manage_plugins_none: "Żadne rozszerzenie nie jest włączone",
  manage_plugins_lead: "Wyłączone rozszerzenie znika z miejsca, a jego dane czekają na ponowne włączenie.",
  // The plugin catalog of a place (design E-KatalogWidzetow): the plugins that are not on yet
  add_plugin_title: "Dodaj rozszerzenie",
  add_plugin_search: "Szukaj rozszerzeń",
  add_plugin_add: "Dodaj do miejsca",
  add_plugin_added: "Dodano do miejsca",
  add_plugin_error: "Nie udało się dodać rozszerzenia.",
  add_plugin_all_added: "Wszystkie rozszerzenia są już w tym miejscu.",
  add_plugin_no_results: "Żadne rozszerzenie nie pasuje do wyszukiwania.",
  manage_layout_title: "Układ pulpitu",
  manage_layout_edit: "Edytuj układ pulpitu",
  // The dashboard layout editor (design E-UkladPulpitu)
  manage_layout_hint: "Dotknij widżetu, aby zmienić rozmiar lub kolejność.",
  manage_layout_save: "Zapisz",
  manage_layout_save_error: "Nie udało się zapisać układu. Spróbuj ponownie.",
  manage_layout_add: "Dodaj widżet",
  manage_layout_size: "Rozmiar",
  manage_layout_size_group: "Rozmiar widżetu",
  manage_layout_size_hint: "Dostępne rozmiary określa rozszerzenie.",
  manage_layout_up: "Wyżej",
  manage_layout_down: "Niżej",
  manage_layout_remove: "Usuń",
  /** "Dodaj" next to a widget in the "Dodaj widżet" sheet; its accessible name adds the widget: "Dodaj: Ogłoszenia". */
  manage_layout_add_one: "Dodaj",
  /** Before the sizes a widget allows: "Rozmiary: 3×3, 3×2". */
  manage_layout_sizes: "Rozmiary:",
  manage_layout_more: "Więcej widżetów? Dodaj rozszerzenie",
  manage_layout_add_none: "Wszystkie widżety są już na pulpicie.",
  manage_members_title: "Członkowie",
  /** After your own name in a list of members: "Jan Kowalski (Ty)". */
  members_you: "(Ty)",
  members_see_all: "Zobacz wszystkich członków",
  members_search: "Szukaj po imieniu",
  members_filter_label: "Filtruj członków",
  /** Filter chips, followed by a count: "Wszyscy 8". */
  members_filter_all: "Wszyscy",
  members_filter_admins: "Administratorzy",
  members_filter_members: "Członkowie",
  members_admin_badge: "Admin",
  /** Before the date a member joined: "W miejscu od 3 paź". */
  members_since: "W miejscu od",
  /** Name of a member's options button, followed by their name. */
  members_options: "Opcje członka",
  members_make_admin: "Nadaj uprawnienia administratora",
  members_revoke_admin: "Odbierz uprawnienia administratora",
  members_remove: "Usuń z miejsca",
  members_remove_title: "Usunąć z miejsca?",
  /** After the member's name: "Anna Nowak straci dostęp…". */
  members_remove_body: "straci dostęp do tego miejsca i jego rozszerzeń.",
  members_empty_search: "Nikt nie pasuje do wyszukiwania.",
  members_role_error: "Nie udało się zmienić uprawnień.",
  members_remove_error: "Nie udało się usunąć członka.",
  members_invite_title: "Zaproś osoby",
  manage_settings_title: "Ustawienia miejsca",
  manage_settings_summary: "Nazwa, rodzaj, zasady dołączania",
  manage_save: "Zapisz zmiany",
  manage_saved: "Zapisano zmiany.",
  manage_save_error: "Nie udało się zapisać zmian.",
  manage_delete: "Usuń miejsce",
  manage_delete_title: "Usunąć to miejsce?",
  manage_delete_body: "Członkowie stracą do niego dostęp, a dane rozszerzeń zostaną usunięte. Tego nie da się cofnąć.",
  manage_delete_confirm: "Usuń",
  manage_delete_error: "Nie udało się usunąć miejsca.",
  build_title: "Rozszerzenie z AI",
  build_entry_title: "Stwórz rozszerzenie z AI",
  build_entry_subtitle: "Opisz, czego potrzebuje miejsce, a AI napisze i sprawdzi rozszerzenie",
  build_lead:
    "Opisz funkcję własnymi słowami. AI napisze rozszerzenie i sprawdzi je jak każde inne. Do publikacji jest szkicem, który widzą tylko administratorzy, a zmieniać je możesz zawsze, także po publikacji.",
  build_request_label: "Czego potrzebuje Twoje miejsce?",
  build_request_placeholder:
    "Np. rezerwacja sali spotkań: mieszkańcy wybierają dzień i godzinę, a administrator widzi listę rezerwacji.",
  build_create: "Stwórz rozszerzenie",
  build_plugins_title: "Rozszerzenia napisane przez AI",
  build_version: "Wersja",
  build_you: "Twoja prośba",
  build_working: "AI pisze rozszerzenie…",
  build_working_attempt: "Sprawdzanie kodu, próba",
  build_working_hint: "To zwykle trwa około minuty. Możesz zamknąć ten ekran i wrócić później: AI pracuje dalej.",
  build_views: ["widok", "widoki", "widoków"],
  build_tools: ["akcja", "akcje", "akcji"],
  build_tables: ["tabela", "tabele", "tabel"],
  build_widgets: ["widżet", "widżety", "widżetów"],
  build_failed_check_failed:
    "AI nie napisało rozszerzenia, które przechodzi sprawdzenie. Opisz to prościej albo inaczej.",
  build_failed_timeout: "AI nie zdążyło w wyznaczonym czasie.",
  build_failed_internal: "Coś poszło nie tak.",
  build_retry: "Spróbuj ponownie",
  build_failed_ai_unavailable: "AI nie jest dostępne na tym serwerze.",
  build_unavailable: "AI nie jest skonfigurowane na tym serwerze, więc nie może pisać rozszerzeń.",
  build_publish: "Opublikuj w miejscu",
  build_update: "Zaktualizuj w miejscu",
  build_published: "W miejscu działa wersja",
  build_draft_note: "Szkic: widzą go tylko administratorzy. Opublikuj go, żeby trafił do użytkowników.",
  build_open: "Otwórz rozszerzenie",
  build_publish_error: "Nie udało się opublikować rozszerzenia.",
  build_change_label: "Co zmienić?",
  build_change_placeholder: "Np. dodaj pole na zdjęcie i pokaż najnowsze wpisy na pulpicie.",
  build_change_send: "Zmień rozszerzenie",
  build_send_error: "Nie udało się wysłać. Spróbuj jeszcze raz.",
  build_rate_limited: "To miejsce wykorzystało dzisiejszy limit próśb do AI. Spróbuj jutro.",
  build_status_working: "AI pisze",
  build_status_draft: "Szkic",
  build_status_published: "Opublikowane",
  build_made_by_ai: "Z AI",
  role_admin: "Administrator",
  role_member: "Członek",
  count_people: ["osoba", "osoby", "osób"],
  count_admins: ["administrator", "administratorów", "administratorów"],
  count_plugins: ["rozszerzenie", "rozszerzenia", "rozszerzeń"],
  count_widgets: ["rozszerzenie", "rozszerzenia", "rozszerzeń"],
  count_places: ["miejsce", "miejsca", "miejsc"],
  count_unread: ["nieprzeczytane", "nieprzeczytane", "nieprzeczytanych"],
  // Android notification channels (shown in the system notification settings)
  push_channel_alerts: "Alerty i ostrzeżenia",
  push_channel_default: "Powiadomienia",
} as const;
