/**
 * All UI text of the app (Polish — the app has one language). Import `t` and read `t.key`;
 * no Polish string literals in components.
 */
export const t = {
  app_name: "Twoje Miejsce",
  meta_login_title: "Logowanie — Twoje Miejsce",
  meta_register_title: "Załóż konto — Twoje Miejsce",
  nav_label: "Główna",
  nav_login: "Zaloguj się",
  nav_open_app: "Otwórz aplikację",
  auth_login_title: "Witaj z powrotem",
  auth_login_lead: "Zaloguj się, aby zobaczyć swoje miejsca.",
  auth_register_title: "Załóż konto",
  auth_name: "Imię i nazwisko",
  auth_email: "Email",
  auth_password: "Hasło",
  auth_submit_login: "Zaloguj się",
  auth_submit_register: "Utwórz konto",
  auth_have_account: "Masz konto?",
  auth_no_account: "Nie masz konta?",
  auth_goto_login: "Zaloguj się",
  auth_goto_register: "Zarejestruj się",
  auth_login_error: "Nieprawidłowy email lub hasło.",
  auth_register_error: "Nie udało się założyć konta. Ten email może być już zajęty.",
  auth_register_lead: "Jedno konto — wszystkie Twoje miejsca w jednej aplikacji.",
  auth_step: "Krok 1 z 2",
  auth_back: "Wróć",
  auth_name_placeholder: "Jan Kowalski",
  auth_email_placeholder: "jan.kowalski@poczta.pl",
  auth_password_placeholder: "Minimum 8 znaków",
  pw_hint_length: "Użyj co najmniej 8 znaków.",
  pw_hint_digit: "Dodaj cyfrę, aby wzmocnić hasło.",
  pw_hint_case: "Dodaj wielką literę, aby wzmocnić hasło.",
  pw_hint_symbol: "Dodaj znak specjalny, aby wzmocnić hasło.",
  pw_strong: "Hasło jest mocne.",
  auth_consent: "Akceptuję regulamin i politykę prywatności.",
  auth_consent_required: "Zaakceptuj regulamin, aby założyć konto.",
  loading: "Ładowanie…",
  sign_out: "Wyloguj",
  notfound_title: "Ta strona nie istnieje",
  notfound_body: "Link może być błędny albo strona została usunięta.",
  notfound_home: "Przejdź na stronę główną",
  meta_notfound_title: "Nie znaleziono strony — Twoje Miejsce",
  meta_communities_title: "Społeczności",
  communities_title: "Społeczności",
  communities_lead: "Miejsca, do których należysz. Każde włącza tylko te funkcje, których potrzebuje.",
  communities_list_label: "Społeczności",
  communities_empty: "Nie ma jeszcze żadnych społeczności.",
  community_features_label: "Funkcje",
  community_features_empty: "Ta społeczność nie ma jeszcze żadnych funkcji.",
  community_back: "Wszystkie społeczności",
  plugin_back: "Wróć do społeczności",
  plugin_load_error: "Nie udało się wczytać tej funkcji.",
  plugin_action_error: "Coś poszło nie tak. Sprawdź formularz i spróbuj ponownie.",
  plugin_unsupported: "Ten element wymaga nowszej wersji aplikacji.",
  plugin_photo_pick: "Wybierz zdjęcie",
  plugin_photo_change: "Zmień zdjęcie",
  plugin_photo_remove: "Usuń zdjęcie",
  plugin_photo_uploading: "Wysyłanie zdjęcia…",
  plugin_photo_error: "Nie udało się wysłać zdjęcia. Spróbuj ponownie.",
  plugin_photo_preview: "Wybrane zdjęcie",
} as const;
