/**
 * All UI text of the app (Polish — the app has one language). Import `t` and read `t.key`;
 * no Polish string literals in components.
 */
export const t = {
  dashboard_greeting: "Dzień dobry",
  dashboard_empty_title: "Nie masz jeszcze miejsca",
  dashboard_empty_body: "Utwórz nowe miejsce albo dołącz do istniejącego.",
  place_create: "Utwórz nowe miejsce",
  place_join: "Dołącz",
  place_current_label: "Twoje miejsce",
  place_set_default: "Ustaw wybrane jako domyślne",
  places_sheet_title: "Twoje miejsca",
  places_title: "Miejsca",
  places_lead: "Miejsca, do których należysz.",
  widgets_empty_title: "Pulpit jest jeszcze pusty",
  widgets_empty_body: "Wkrótce pojawią się tu widżety tego miejsca.",
  create_title: "Nowe miejsce",
  create_name: "Nazwa",
  create_submit: "Utwórz miejsce",
  create_error: "Nie udało się utworzyć miejsca.",
  join_title: "Dołącz do miejsca",
  join_body: "Dołączanie do miejsca będzie dostępne wkrótce.",
  account_title: "Konto",
  account_body: "Ustawienia konta będą dostępne wkrótce.",
  back: "Wróć",
  tab_dashboard: "Pulpit",
  tab_places: "Miejsca",
  tab_account: "Konto",
  nav_main: "Nawigacja główna",
  close: "Zamknij",
  place_default_badge: "Domyślne",
  first_place_eyebrow: "Brak miejsc na koncie",
  first_place_title: "Dołącz do swojego pierwszego miejsca",
  first_place_how: "Jak chcesz dołączyć?",
  first_place_qr: "Zeskanuj kod QR",
  first_place_qr_hint: "Z plakatu, tablicy lub ekranu",
  first_place_code: "Wpisz kod zaproszeniowy",
  first_place_code_hint: "6-znakowy kod od administratora",
  first_place_link: "Wklej link",
  first_place_link_hint: "Link z wiadomości lub e-maila",
  first_place_invites: "Zaproszenia",
  first_place_invites_hint: "Od innych użytkowników",
  first_place_create_own: "Utwórz własne miejsce",
  account_button: "Konto",
  place_role_admin: "Administrator",
  place_role_member: "Członek",
  app_name: "Twoje Miejsce",
  meta_login_title: "Logowanie — Twoje Miejsce",
  meta_register_title: "Załóż konto — Twoje Miejsce",
  nav_label: "Główna",
  nav_login: "Zaloguj się",
  nav_open_app: "Otwórz aplikację",
  auth_login_title: "Witaj z powrotem",
  auth_login_lead: "Zaloguj się, aby zobaczyć swoje miejsca.",
  auth_register_title: "Załóż konto",
  auth_name: "Imię i nazwisko",
  auth_email: "Email",
  auth_password: "Hasło",
  auth_submit_login: "Zaloguj się",
  auth_submit_register: "Utwórz konto",
  auth_have_account: "Masz konto?",
  auth_no_account: "Nie masz konta?",
  auth_goto_login: "Zaloguj się",
  auth_goto_register: "Zarejestruj się",
  auth_login_error: "Nieprawidłowy email lub hasło.",
  auth_register_error: "Nie udało się założyć konta. Ten email może być już zajęty.",
  auth_register_lead: "Jedno konto — wszystkie Twoje miejsca w jednej aplikacji.",
  auth_step: "Krok 1 z 2",
  auth_back: "Wróć",
  auth_name_placeholder: "Jan Kowalski",
  auth_email_placeholder: "jan.kowalski@poczta.pl",
  auth_password_placeholder: "Minimum 8 znaków",
  pw_hint_length: "Użyj co najmniej 8 znaków.",
  pw_hint_digit: "Dodaj cyfrę, aby wzmocnić hasło.",
  pw_hint_case: "Dodaj wielką literę, aby wzmocnić hasło.",
  pw_hint_symbol: "Dodaj znak specjalny, aby wzmocnić hasło.",
  pw_strong: "Hasło jest mocne.",
  auth_consent: "Akceptuję regulamin i politykę prywatności.",
  auth_consent_required: "Zaakceptuj regulamin, aby założyć konto.",
  loading: "Ładowanie…",
  sign_out: "Wyloguj",
  notfound_title: "Ta strona nie istnieje",
  notfound_body: "Link może być błędny albo strona została usunięta.",
  notfound_home: "Przejdź na stronę główną",
  meta_notfound_title: "Nie znaleziono strony — Twoje Miejsce",
  community_features_label: "Funkcje",
  community_features_empty: "Ta społeczność nie ma jeszcze żadnych funkcji.",
  community_dashboard_label: "Pulpit miejsca",
  dashboard_edit: "Edytuj pulpit",
  dashboard_done: "Gotowe",
  dashboard_edit_hint: "Przeciągnij kafelek albo użyj strzałek. Kolejność zobaczą wszyscy mieszkańcy.",
  dashboard_drag: "Przeciągnij",
  dashboard_move_earlier: "Przesuń wcześniej",
  dashboard_move_later: "Przesuń dalej",
  dashboard_save_error: "Nie udało się zapisać kolejności. Spróbuj ponownie.",
  plugin_load_error: "Nie udało się wczytać tej funkcji.",
  plugin_action_error: "Coś poszło nie tak. Sprawdź formularz i spróbuj ponownie.",
  plugin_unsupported: "Ten element wymaga nowszej wersji aplikacji.",
  plugin_photo_pick: "Wybierz zdjęcie",
  plugin_photo_change: "Zmień zdjęcie",
  plugin_photo_remove: "Usuń zdjęcie",
  plugin_photo_uploading: "Wysyłanie zdjęcia…",
  plugin_photo_error: "Nie udało się wysłać zdjęcia. Spróbuj ponownie.",
  plugin_photo_preview: "Wybrane zdjęcie",
  // Android notification channels (shown in the system notification settings)
  push_channel_alerts: "Alerty i ostrzeżenia",
  push_channel_default: "Powiadomienia",
} as const;
